version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NEST
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nest-api:
    container_name: nest-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    env_file:
      - .env
    depends_on:
      - database
volumes:
  postgres-data: