version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vest
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    env_file:
      - .env
    depends_on:
      - db
